language: c
os:
  - linux
sudo: enabled
addons:
  apt:
    packages:
      - curl

before_install:
  - sudo apt-get update -qq
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 ~/aarch64-linux-android-4.9/
  - sudo chmod -R a+x *

script:  
  
  - export ARCH=arm64
  - export CROSS_COMPILE=~/aarch64-linux-android-4.9/bin/aarch64-linux-android-
  - KERNEL_DIR=$PWD/kernel_huawei_msm8937
  - IMAGE=$KERNEL_DIR/arch/arm64/boot/Image.gz-dtb
  - make ARCH=arm64 msmcortex_defconfig
  - make ARCH=arm64 Image.gz-dtb 

after_success:
  - curl --upload-file arch/arm64/boot/Image.gz-dtb https://transfer.sh/Image.gz-dtb
  
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  
  on:
    tags: true
    repo: algphello/kernel_huawei_msm8937
    branch: master

branches:
  except:
    - /^(?i:untagged)-.*$/
