language: c
os:
  - linux
sudo: enabled
addons:
  apt:
    packages:
      - curl

before_install:
  - sudo apt-get update -y
  - sudo apt-get install -y python gnupg flex bison gperf libsdl1.2-dev squashfs-tools build-essential zip unzip libncurses5-dev zlib1g-dev openjdk-8-jre openjdk-8-jdk pngcrush schedtool libxml2 libxml2-utils xsltproc lzop libc6-dev g++-multilib lib32z1-dev lib32ncurses5-dev gcc-multilib liblz4-* pngquant ncurses-dev texinfo gcc gperf patch libtool automake g++ gawk subversion expat libexpat1-dev python-all-dev bc libcloog-isl-dev libcap-dev autoconf libgmp-dev pkg-config libmpc-dev libmpfr-dev lzma* liblzma* w3m maven ncftp htop imagemagick libssl-dev clang cmake axel re2c libesd0-dev
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 ~/aarch64-linux-android-4.9/
  - git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 ~/clang/
  - sudo chmod -R a+x *

script:  
  
  - export ARCH=arm64
  - export CC=clang
  - export CLANG_TRIPLE=~/clang/bin/clang/clang-4679922/bin/llvm-
  - export CROSS_COMPILE=~/aarch64-linux-android-4.9/bin/aarch64-linux-android-
  - KERNEL_DIR=$PWD/kernel_huawei_msm8937
  - IMAGE=$KERNEL_DIR/arch/arm64/boot/Image.gz-dtb
  - make ARCH=arm64 msm-perf_defconfig
  - make -j$(nproc --all) ARCH=arm64 \ 
                      CC="~/clang/clang-4679922/bin/clang" \
                      CLANG_TRIPLE=llvm- \
                      CROSS_COMPILE="~/aarch64-linux-android-4.9/bin/aarch64-linux-android-"
after_success:
  - curl --upload-file arch/arm64/boot/Image.gz-dtb https://transfer.sh/Image.gz-dtb
  
deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GitOAUTHToken_KERNEL"
  
  on:
    tags: true
    repo: algphello/kernel_huawei_msm8937
    branch: master

branches:
  except:
    - /^(?i:untagged)-.*$/

