obj-$(CONFIG_PIL_Q6V5_MSS) += pil_q6v5_mss_ultils.o
obj-$(CONFIG_PIL_Q6V5_MSS_LOG) += pil_q6v5_mss_log.o pil_q6v5_mss_ultils.o
obj-$(CONFIG_PIL_Q6V5_MSS_CTL) += pil_q6v5_mss_ctl.o pil_q6v5_mss_ultils.o