/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*-------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = 1.1
 *-----------------------------------------------------------------------*/

#ifndef _PANEL_AUM_TL10_VA_TCL_CSOT_FT8613_5P7_HD_VIDEO_H_

#define _PANEL_AUM_TL10_VA_TCL_CSOT_FT8613_5P7_HD_VIDEO_H_
/*-----------------------------------------------------------------------*/
/* HEADER files                                                          */
/*-----------------------------------------------------------------------*/
#include "panel.h"

#include "lcdkit_bias_ic_common.h"

#include "lcd_bl.h"

/*-----------------------------------------------------------------------*/
/* Panel configuration                                                   */
/*-----------------------------------------------------------------------*/
static struct panel_config aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_panel_data = {
        "lcdkit_aum_tl10_va_tcl_csot_ft8613_5p7_hd_video", "dsi:0:", 
        "tcl_csot_ft8613_5p7_hd_video", 10, 0, "DISPLAY_1", 0, 667000000, 
        60, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel resolution                                                      */
/*-----------------------------------------------------------------------*/
static struct panel_resolution aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_panel_res = {
        720, 1440, 110, 108, 4, 0, 16, 16, 4, 0, 0, 0, 0, 0, 0, 0, 
        0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel color information                                               */
/*-----------------------------------------------------------------------*/
static struct color_info aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_color = {
        24, 0, 0x00, 0, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel on/off command                                                  */
/*-----------------------------------------------------------------------*/
static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd0[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x00, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd1[] = {
    0x04, 0x00, 0x39, 0xC0,
    0xff, 0x87, 0x16, 0x01,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd2[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x80, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd3[] = {
    0x03, 0x00, 0x39, 0xC0,
    0xff, 0x87, 0x16, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd4[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x80, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd5[] = {
    0x10, 0x00, 0x39, 0xC0,
    0xC0, 0x00, 0xA5, 0x00,
    0x10, 0x10, 0x00, 0xA5,
    0x10, 0x10, 0x00, 0xA5,
    0x00, 0x10, 0x10, 0x00,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd6[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x80, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd7[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xF3, 0x70, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd8[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x90, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd9[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xC5, 0x55, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd10[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xA0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd11[] = {
    0x08, 0x00, 0x39, 0xC0,
    0xC0, 0x0D, 0x01, 0x01,
    0x01, 0x01, 0x24, 0x09,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd12[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xD0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd13[] = {
    0x08, 0x00, 0x39, 0xC0,
    0xC0, 0x0D, 0x01, 0x01,
    0x01, 0x01, 0x24, 0x09,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd14[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xA8, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd15[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xF5, 0x22, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd16[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x82, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd17[] = {
    0x04, 0x00, 0x39, 0xC0,
    0xA5, 0x00, 0x00, 0x0C,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd18[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x87, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd19[] = {
    0x05, 0x00, 0x39, 0xC0,
    0xA5, 0x00, 0x07, 0x77,
    0x00, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd20[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xA0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd21[] = {
    0x09, 0x00, 0x39, 0xC0,
    0xCE, 0x00, 0x05, 0x01,
    0x01, 0x01, 0x01, 0x3F,
    0x0A, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd22[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xA0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd23[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xB3, 0x32, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd24[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xA6, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd25[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xB3, 0x58, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd26[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x80, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd27[] = {
    0x0D, 0x00, 0x39, 0xC0,
    0xC2, 0x82, 0x00, 0x00,
    0x81, 0x81, 0x00, 0x00,
    0x81, 0x83, 0x00, 0x3f,
    0xB0, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd28[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xB0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd29[] = {
    0x10, 0x00, 0x39, 0xC0,
    0xC2, 0x82, 0x00, 0x00,
    0x07, 0x88, 0x81, 0x01,
    0x00, 0x07, 0x88, 0x00,
    0x02, 0x00, 0x07, 0x88,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd30[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xC0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd31[] = {
    0x06, 0x00, 0x39, 0xC0,
    0xC2, 0x01, 0x03, 0x00,
    0x07, 0x88, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd32[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xDA, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd33[] = {
    0x03, 0x00, 0x39, 0xC0,
    0xC2, 0x33, 0x33, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd34[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x82, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd35[] = {
    0x04, 0x00, 0x39, 0xC0,
    0xa5, 0x00, 0x00, 0x00,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd36[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x87, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd37[] = {
    0x05, 0x00, 0x39, 0xC0,
    0xa5, 0x00, 0x07, 0x77,
    0x77, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd38[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x88, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd39[] = {
    0x03, 0x00, 0x39, 0xC0,
    0xc3, 0x22, 0x22, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd40[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x98, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd41[] = {
    0x03, 0x00, 0x39, 0xC0,
    0xc3, 0x22, 0x22, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd42[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xAA, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd43[] = {
    0x03, 0x00, 0x39, 0xC0,
    0xC3, 0x99, 0x9C, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd44[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x90, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd45[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xC5, 0x55, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd46[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x80, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd47[] = {
    0x0A, 0x00, 0x39, 0xC0,
    0xCE, 0x25, 0x00, 0x74,
    0x00, 0x78, 0xFF, 0x00,
    0x00, 0x05, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd48[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x90, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd49[] = {
    0x09, 0x00, 0x39, 0xC0,
    0xCE, 0x00, 0x5C, 0x0C,
    0xE4, 0x00, 0x5C, 0x00,
    0x00, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd50[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xB0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd51[] = {
    0x07, 0x00, 0x39, 0xC0,
    0xCE, 0x00, 0x00, 0x60,
    0x60, 0x00, 0x60, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd52[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x80, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd53[] = {
    0x0D, 0x00, 0x39, 0xC0,
    0xCC, 0x02, 0x03, 0x06,
    0x07, 0x08, 0x09, 0x0A,
    0x0B, 0x0C, 0x0D, 0x0E,
    0x0F, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd54[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x90, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd55[] = {
    0x0D, 0x00, 0x39, 0xC0,
    0xCC, 0x03, 0x02, 0x09,
    0x08, 0x07, 0x06, 0x0F,
    0x0E, 0x0D, 0x0C, 0x0B,
    0x0A, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd56[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xA0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd57[] = {
    0x10, 0x00, 0x39, 0xC0,
    0xCC, 0x1A, 0x1B, 0x1C,
    0x1D, 0x1E, 0x1F, 0x18,
    0x19, 0x20, 0x21, 0x14,
    0x15, 0x16, 0x17, 0x04,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd58[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xB0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd59[] = {
    0x06, 0x00, 0x39, 0xC0,
    0xCC, 0x22, 0x22, 0x22,
    0x22, 0x22, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd60[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x80, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd61[] = {
    0x09, 0x00, 0x39, 0xC0,
    0xCB, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd62[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x90, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd63[] = {
    0x10, 0x00, 0x39, 0xC0,
    0xCB, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd64[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xA0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd65[] = {
    0x10, 0x00, 0x39, 0xC0,
    0xCB, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd66[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xB0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd67[] = {
    0x03, 0x00, 0x39, 0xC0,
    0xCB, 0x00, 0x00, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd68[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xC0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd69[] = {
    0x10, 0x00, 0x39, 0xC0,
    0xCB, 0x05, 0x05, 0x05,
    0x05, 0x05, 0x05, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x00, 0x05, 0x05, 0x05,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd70[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xD0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd71[] = {
    0x10, 0x00, 0x39, 0xC0,
    0xCB, 0x00, 0x00, 0x00,
    0x05, 0x05, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
    0x0A, 0x00, 0x00, 0x00,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd72[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xE0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd73[] = {
    0x03, 0x00, 0x39, 0xC0,
    0xCB, 0x00, 0x00, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd74[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xF0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd75[] = {
    0x09, 0x00, 0x39, 0xC0,
    0xCB, 0xFF, 0x0F, 0x00,
    0x3F, 0x30, 0x30, 0x30,
    0x00, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd76[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x80, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd77[] = {
    0x10, 0x00, 0x39, 0xC0,
    0xCD, 0x22, 0x22, 0x22,
    0x22, 0x22, 0x01, 0x13,
    0x14, 0x1B, 0x05, 0x03,
    0x17, 0x18, 0x18, 0x22,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd78[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x90, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd79[] = {
    0x04, 0x00, 0x39, 0xC0,
    0xCD, 0x0F, 0x0E, 0x0D,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd80[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xA0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd81[] = {
    0x10, 0x00, 0x39, 0xC0,
    0xCD, 0x22, 0x22, 0x22,
    0x22, 0x22, 0x02, 0x13,
    0x14, 0x1B, 0x06, 0x04,
    0x17, 0x18, 0x18, 0x22,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd82[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xB0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd83[] = {
    0x04, 0x00, 0x39, 0xC0,
    0xCD, 0x0F, 0x0E, 0x0D,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd84[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x81, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd85[] = {
    0x0D, 0x00, 0x39, 0xC0,
    0xF3, 0x40, 0x89, 0xC0,
    0x40, 0x89, 0xC0, 0x40,
    0x81, 0xC0, 0x40, 0x81,
    0xC0, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd86[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x00, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd87[] = {
    0x19, 0x00, 0x39, 0xC0,
    0xE1, 0x00, 0x06, 0x18,
    0x2A, 0x36, 0x41, 0x54,
    0x63, 0x6A, 0x72, 0x7D,
    0x87, 0x70, 0x68, 0x65,
    0x5E, 0x51, 0x45, 0x37,
    0x2D, 0x25, 0x16, 0x08,
    0x07, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd88[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x00, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd89[] = {
    0x19, 0x00, 0x39, 0xC0,
    0xE2, 0x00, 0x06, 0x18,
    0x2A, 0x36, 0x41, 0x54,
    0x63, 0x6A, 0x72, 0x7D,
    0x87, 0x70, 0x68, 0x65,
    0x5E, 0x51, 0x45, 0x37,
    0x2D, 0x25, 0x16, 0x08,
    0x07, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd90[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x80, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd91[] = {
    0x0B, 0x00, 0x39, 0xC0,
    0xC5, 0x00, 0xC1, 0xDD,
    0xC4, 0x14, 0x1E, 0x00,
    0x55, 0x50, 0x05, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd92[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x90, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd93[] = {
    0x0B, 0x00, 0x39, 0xC0,
    0xC5, 0x77, 0x1E, 0x14,
    0x00, 0x88, 0x10, 0x4C,
    0x53, 0x55, 0x50, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd94[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x00, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd95[] = {
    0x03, 0x00, 0x39, 0xC0,
    0xD8, 0x31, 0x31, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd96[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x00, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd97[] = {
    0x06, 0x00, 0x39, 0xC0,
    0xD9, 0x80, 0x8E, 0x8E,
    0x8E, 0x8E, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd98[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xd1, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd99[] = {
    0x0D, 0x00, 0x39, 0xC0,
    0xcf, 0x02, 0x04, 0x00,
    0x0A, 0x00, 0x14, 0x02,
    0x04, 0x00, 0x0C, 0x00,
    0x12, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd100[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xc0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd101[] = {
    0x03, 0x00, 0x39, 0xC0,
    0xc0, 0x11, 0x11, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd102[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x00, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd103[] = {
    0x05, 0x00, 0x39, 0xC0,
    0x2a, 0x00, 0x00, 0x02,
    0xcf, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd104[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x00, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd105[] = {
    0x05, 0x00, 0x39, 0xC0,
    0x2b, 0x00, 0x00, 0x05,
    0x9f, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd106[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xa1, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd107[] = {
    0x05, 0x00, 0x39, 0xC0,
    0xb3, 0x02, 0xd0, 0x05,
    0xa0, 0xFF, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd108[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x92, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd109[] = {
    0x03, 0x00, 0x39, 0xC0,
    0xff, 0x20, 0x02, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd110[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0xB0, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd111[] = {
    0x03, 0x00, 0x39, 0xC0,
    0xCA, 0x05, 0x05, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd112[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x00, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd113[] = {
    0x03, 0x00, 0x39, 0xC0,
    0xD1, 0x00, 0x01, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd114[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x8d, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd115[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xf5, 0x21, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd116[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x00, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd117[] = {
    0x04, 0x00, 0x39, 0xC0,
    0xff, 0x00, 0x00, 0x00,
   };


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd118[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x80, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd119[] = {
    0x03, 0x00, 0x39, 0xC0,
    0xff, 0x00, 0x00, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd120[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x55, 0x00, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd121[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x53, 0x2C, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd122[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x11, 0x00, 0xFF, 0xFF};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd123[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x29, 0x00, 0xFF, 0xFF};




static struct mipi_dsi_cmd aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_command[] = {
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd0, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd1, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd2, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd3, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd4, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd5, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd6, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd7, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd8, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd9, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd10, 0x00},
{0xc, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd11, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd12, 0x00},
{0xc, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd13, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd14, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd15, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd16, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd17, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd18, 0x00},
{0xc, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd19, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd20, 0x00},
{0x10, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd21, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd22, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd23, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd24, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd25, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd26, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd27, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd28, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd29, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd30, 0x00},
{0xc, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd31, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd32, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd33, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd34, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd35, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd36, 0x00},
{0xc, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd37, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd38, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd39, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd40, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd41, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd42, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd43, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd44, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd45, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd46, 0x00},
{0x10, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd47, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd48, 0x00},
{0x10, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd49, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd50, 0x00},
{0xc, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd51, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd52, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd53, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd54, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd55, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd56, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd57, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd58, 0x00},
{0xc, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd59, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd60, 0x00},
{0x10, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd61, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd62, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd63, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd64, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd65, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd66, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd67, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd68, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd69, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd70, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd71, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd72, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd73, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd74, 0x00},
{0x10, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd75, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd76, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd77, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd78, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd79, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd80, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd81, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd82, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd83, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd84, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd85, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd86, 0x00},
{0x20, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd87, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd88, 0x00},
{0x20, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd89, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd90, 0x00},
{0x10, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd91, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd92, 0x00},
{0x10, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd93, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd94, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd95, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd96, 0x00},
{0xc, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd97, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd98, 0x00},
{0x14, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd99, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd100, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd101, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd102, 0x00},
{0xc, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd103, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd104, 0x00},
{0xc, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd105, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd106, 0x00},
{0xc, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd107, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd108, 0x05},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd109, 0x05},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd110, 0x05},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd111, 0x05},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd112, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd113, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd114, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd115, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd116, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd117, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd118, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd119, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd120, 0x05},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd121, 0x00},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd122, 0x78},
{0x8, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_on_cmd123, 0x14}
};
#define AUM_TL10_VA_TCL_CSOT_FT8613_5P7_HD_VIDEO_ON_COMMAND 124


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_off_cmd0[] = {
    0x28, 0x00, 0x05, 0x80};


static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_off_cmd1[] = {
    0x10, 0x00, 0x05, 0x80};




static struct mipi_dsi_cmd aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_off_command[] = {
{0x4, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_off_cmd0, 0x14},
{0x4, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_off_cmd1, 0x78}
};
#define AUM_TL10_VA_TCL_CSOT_FT8613_5P7_HD_VIDEO_OFF_COMMAND 2


static struct command_state aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_state = {
        0, 1 
};

/*-----------------------------------------------------------------------*/
/* Command mode panel                                                    */
/*-----------------------------------------------------------------------*/
static struct commandpanel_info aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_command_panel = {
        1, 1, 1, 0, 0, 0x2c, 0, 0, 0, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Video mode panel                                                      */
/*-----------------------------------------------------------------------*/
static struct videopanel_info aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_video_panel = {
        1, 0, 0, 0, 1, 1, 2, 0, 0x9 
};

/*-----------------------------------------------------------------------*/
/* Lane configuration                                                    */
/*-----------------------------------------------------------------------*/
static struct lane_configuration aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_lane_config = {
        3, 0, 1, 1, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel timing                                                          */
/*-----------------------------------------------------------------------*/
static const uint32_t aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_timings[]= {
        0xB4, 0x2A, 0x1C, 0x00, 0x54, 0x58, 0x20, 0x2E, 0x20, 0x03, 0x04, 0x00 
};

static struct panel_timing aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_timing_info = {
        0, 4, 0x03, 0x23 
};

/*-----------------------------------------------------------------------*/
/* Panel reset sequence                                                  */
/*-----------------------------------------------------------------------*/
static struct panel_reset_sequence aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_reset_seq = {
    { 1, 0, 1, }, { 5, 2, 5, }, 2
};

/*-----------------------------------------------------------------------*/
/* Backlight setting                                                     */
/*-----------------------------------------------------------------------*/
static struct backlight aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_backlight = {
        2, 2, 255, 1, 2, 0 
};

/*-----------------------------------------------------------------------*/
/* Labibb setting                                                        */
/*-----------------------------------------------------------------------*/
static struct labibb_desc aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_labibb = {
        0, 1, 5500000, 5500000, 5500000, 5500000, 2, 0, 1, 0 
};

/*-----------------------------------------------------------------------*/
/* turn on backlight delay                                               */
/*-----------------------------------------------------------------------*/
int aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_mdp_pipe_type  = MDSS_MDP_PIPE_TYPE_RGB;

int aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_dsi_pll_type  = DSI_PLL_TYPE_28NM;

int aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_mipi_signature  = 0xffff;

static const uint32_t aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_regulator_setting[]= {
        0x03, 0x08, 0x07, 0x00, 0x20, 0x07, 0x01 
};

/*-----------------------------------------------------------------------*/
/* platform Config                                                       */
/*-----------------------------------------------------------------------*/
static struct lcdkit_platform_config aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_panel_platform_config = {
        3, 1, 0, 0, 0, 0, 0x200, 0x20, 0, 99, 0, 60, 0, 0, 0, 124, 
        127, 98, 0, 0, 0, 0, 5500000, 5500000, 70, 20, 0, 0, 0, 1, 0, 
        0, 0 
};

/*-----------------------------------------------------------------------*/
/* misc Information                                                      */
/*-----------------------------------------------------------------------*/
static struct lcdkit_misc_info aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_panel_misc_info = {
        0, 0, 2, 0x01, 0x04, 0x01, 0x01, 1, 0, 1 
};

/*-----------------------------------------------------------------------*/
/* delay ctrl                                                            */
/*-----------------------------------------------------------------------*/
static struct lcdkit_delay_ctrl aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_panel_delay_ctrl = {
        0, 0, 0, 11, 2, 0, 0, 0, 0, 0, 0, 20, 0, 50 
};

static char aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_backlight_cmd0[] = {
    0x51, 0x00, 0x15, 0x80};




static struct mipi_dsi_cmd aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_backlight_command[] = {
{0x4, aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_backlight_cmd0, 0x00}
};
#define AUM_TL10_VA_TCL_CSOT_FT8613_5P7_HD_VIDEO_BACKLIGHT_COMMAND 1


static struct lcd_bias_voltage_info aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_bias_ic0 = {
"hw_sm5109", 0x3e, 2, 1, 0x0c, 0x00, 0x01, 0x32, 0x12, 0x3f, 0x1f, 0x03, 0x03, 0xc3, 0x03, 0x43, 0x43, 0x00, 0x00, 0x00, 0
};
static struct lcd_bias_voltage_info aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_bias_ic1 = {
"hw_ocp2131", 0x3e, 2, 1, 0x06, 0x00, 0x01, 0x12, 0x12, 0x1f, 0x1f, 0x03, 0x33, 0x33, 0x00, 0x00, 0x00, 0xff, 0x80, 0x80, 0
};

static struct lcd_bias_voltage_info * aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_bias_ic_array[] = {
&aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_bias_ic0,
&aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_bias_ic1
};

#define AUM_TL10_VA_TCL_CSOT_FT8613_5P7_HD_VIDEO_BIAS_IC_ARRAY 2


static struct backlight_ic_info * aum_tl10_va_tcl_csot_ft8613_5p7_hd_video_backlight_ic_array[0];
 
#define AUM_TL10_VA_TCL_CSOT_FT8613_5P7_HD_VIDEO_BACKLIGHT_IC_ARRAY 0


#endif /*_PANEL_AUM_TL10_VA_TCL_CSOT_FT8613_5P7_HD_VIDEO_H_*/
