/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*-------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = 1.1
 *-----------------------------------------------------------------------*/

#ifndef _PANEL_CPN_L01_VA_INX_NT51021_8P0_1200P_VIDEO_H_

#define _PANEL_CPN_L01_VA_INX_NT51021_8P0_1200P_VIDEO_H_
/*-----------------------------------------------------------------------*/
/* HEADER files                                                          */
/*-----------------------------------------------------------------------*/
#include "panel.h"

#include "lcdkit_bias_ic_common.h"

#include "lcd_bl.h"

/*-----------------------------------------------------------------------*/
/* Panel configuration                                                   */
/*-----------------------------------------------------------------------*/
static struct panel_config cpn_l01_va_inx_nt51021_8p0_1200p_video_panel_data = {
        "lcdkit_cpn_l01_va_inx_nt51021_8p0_1200p_video", "dsi:0:", 
        "inx_nt51021_8p0_1200p_video", 10, 0, "DISPLAY_1", 0, 960470000, 
        60, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel resolution                                                      */
/*-----------------------------------------------------------------------*/
static struct panel_resolution cpn_l01_va_inx_nt51021_8p0_1200p_video_panel_res = {
        1200, 1920, 64, 36, 4, 0, 102, 22, 2, 0, 0, 0, 0, 0, 0, 0, 
        0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel color information                                               */
/*-----------------------------------------------------------------------*/
static struct color_info cpn_l01_va_inx_nt51021_8p0_1200p_video_color = {
        24, 0, 0x00, 0, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel on/off command                                                  */
/*-----------------------------------------------------------------------*/
static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd0[] = {
    0x8F, 0xA5, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd1[] = {
    0x01, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd2[] = {
    0x8F, 0xA5, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd3[] = {
    0x83, 0xBB, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd4[] = {
    0x84, 0x22, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd5[] = {
    0xA1, 0xFF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd6[] = {
    0xA2, 0xF9, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd7[] = {
    0xA3, 0xF2, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd8[] = {
    0xA4, 0xED, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd9[] = {
    0xA5, 0xE8, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd10[] = {
    0xA6, 0xE1, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd11[] = {
    0xA7, 0xDE, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd12[] = {
    0xA8, 0xDA, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd13[] = {
    0xA9, 0xD3, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd14[] = {
    0xAA, 0xCF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd15[] = {
    0xB4, 0x20, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd16[] = {
    0xB5, 0x32, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd17[] = {
    0xB6, 0x29, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd18[] = {
    0xAD, 0x06, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd19[] = {
    0x9A, 0x10, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd20[] = {
    0x94, 0xB8, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd21[] = {
    0x95, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd22[] = {
    0x9A, 0x10, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd23[] = {
    0x96, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd24[] = {
    0x90, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd25[] = {
    0x83, 0xAA, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd26[] = {
    0x84, 0x11, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd27[] = {
    0xA9, 0x4B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd28[] = {
    0x83, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd29[] = {
    0x84, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd30[] = {
    0x8C, 0x04, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd31[] = {
    0xFD, 0x53, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd32[] = {
    0xFA, 0x0E, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd33[] = {
    0x83, 0xAA, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd34[] = {
    0x84, 0x11, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd35[] = {
    0xC0, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd36[] = {
    0xC1, 0x01, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd37[] = {
    0xC2, 0x0B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd38[] = {
    0xC3, 0x17, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd39[] = {
    0xC4, 0x22, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd40[] = {
    0xC5, 0x2A, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd41[] = {
    0xC6, 0x32, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd42[] = {
    0xC7, 0x38, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd43[] = {
    0xC8, 0x3E, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd44[] = {
    0xC9, 0x8D, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd45[] = {
    0xCA, 0x8D, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd46[] = {
    0xCB, 0xA0, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd47[] = {
    0xCC, 0xAF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd48[] = {
    0xCD, 0xB3, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd49[] = {
    0xCE, 0xAC, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd50[] = {
    0xCF, 0xAF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd51[] = {
    0xD0, 0xAD, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd52[] = {
    0xD1, 0xB1, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd53[] = {
    0xD2, 0xBB, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd54[] = {
    0xD3, 0xCF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd55[] = {
    0xD4, 0xCF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd56[] = {
    0xD5, 0x6B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd57[] = {
    0xD6, 0x70, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd58[] = {
    0xD7, 0x73, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd59[] = {
    0xD8, 0x7C, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd60[] = {
    0xD9, 0x80, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd61[] = {
    0xDA, 0x89, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd62[] = {
    0xDB, 0x95, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd63[] = {
    0xDC, 0xB3, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd64[] = {
    0xDD, 0xB4, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd65[] = {
    0xDE, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd66[] = {
    0xDF, 0x20, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd67[] = {
    0xE0, 0x39, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd68[] = {
    0xE1, 0x3A, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd69[] = {
    0xE2, 0x44, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd70[] = {
    0xE3, 0x4E, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd71[] = {
    0xE4, 0x5B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd72[] = {
    0xE5, 0x65, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd73[] = {
    0xE6, 0x6B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd74[] = {
    0xE7, 0x71, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd75[] = {
    0xE8, 0x77, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd76[] = {
    0xE9, 0xD7, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd77[] = {
    0xEA, 0xD4, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd78[] = {
    0xEB, 0xEB, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd79[] = {
    0xEC, 0xFC, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd80[] = {
    0xED, 0xFF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd81[] = {
    0xEE, 0xF9, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd82[] = {
    0xEF, 0xFB, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd83[] = {
    0xF0, 0xF9, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd84[] = {
    0xF1, 0xFD, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd85[] = {
    0xF2, 0x06, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd86[] = {
    0xF3, 0x1C, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd87[] = {
    0xF4, 0x1B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd88[] = {
    0xF5, 0x91, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd89[] = {
    0xF6, 0x96, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd90[] = {
    0xF7, 0x99, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd91[] = {
    0xF8, 0xA2, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd92[] = {
    0xF9, 0xA7, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd93[] = {
    0xFA, 0xAD, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd94[] = {
    0xFB, 0xB1, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd95[] = {
    0xFC, 0xB3, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd96[] = {
    0xFD, 0xB4, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd97[] = {
    0xFE, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd98[] = {
    0xFF, 0x2E, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd99[] = {
    0x83, 0xBB, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd100[] = {
    0x84, 0x22, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd101[] = {
    0xC0, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd102[] = {
    0xC1, 0x01, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd103[] = {
    0xC2, 0x0B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd104[] = {
    0xC3, 0x17, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd105[] = {
    0xC4, 0x22, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd106[] = {
    0xC5, 0x2A, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd107[] = {
    0xC6, 0x32, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd108[] = {
    0xC7, 0x38, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd109[] = {
    0xC8, 0x3E, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd110[] = {
    0xC9, 0x8D, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd111[] = {
    0xCA, 0x90, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd112[] = {
    0xCB, 0xA3, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd113[] = {
    0xCC, 0xB2, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd114[] = {
    0xCD, 0xB6, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd115[] = {
    0xCE, 0xB2, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd116[] = {
    0xCF, 0xB5, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd117[] = {
    0xD0, 0xB3, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd118[] = {
    0xD1, 0xBF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd119[] = {
    0xD2, 0xCE, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd120[] = {
    0xD3, 0xE7, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd121[] = {
    0xD4, 0xEC, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd122[] = {
    0xD5, 0x7C, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd123[] = {
    0xD6, 0x82, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd124[] = {
    0xD7, 0x88, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd125[] = {
    0xD8, 0x90, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd126[] = {
    0xD9, 0x98, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd127[] = {
    0xDA, 0x9F, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd128[] = {
    0xDB, 0xAA, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd129[] = {
    0xDC, 0xC7, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd130[] = {
    0xDD, 0xCA, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd131[] = {
    0xDE, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd132[] = {
    0xDF, 0x20, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd133[] = {
    0xE0, 0x39, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd134[] = {
    0xE1, 0x3A, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd135[] = {
    0xE2, 0x44, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd136[] = {
    0xE3, 0x4E, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd137[] = {
    0xE4, 0x5B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd138[] = {
    0xE5, 0x65, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd139[] = {
    0xE6, 0x6B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd140[] = {
    0xE7, 0x71, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd141[] = {
    0xE8, 0x77, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd142[] = {
    0xE9, 0xD7, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd143[] = {
    0xEA, 0xD7, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd144[] = {
    0xEB, 0xEE, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd145[] = {
    0xEC, 0xFF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd146[] = {
    0xED, 0x02, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd147[] = {
    0xEE, 0xFF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd148[] = {
    0xEF, 0x01, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd149[] = {
    0xF0, 0xFF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd150[] = {
    0xF1, 0x0B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd151[] = {
    0xF2, 0x19, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd152[] = {
    0xF3, 0x34, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd153[] = {
    0xF4, 0x38, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd154[] = {
    0xF5, 0xA2, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd155[] = {
    0xF6, 0xA8, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd156[] = {
    0xF7, 0xAE, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd157[] = {
    0xF8, 0xB6, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd158[] = {
    0xF9, 0xBF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd159[] = {
    0xFA, 0xC4, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd160[] = {
    0xFB, 0xC7, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd161[] = {
    0xFC, 0xC7, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd162[] = {
    0xFD, 0xCA, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd163[] = {
    0xFE, 0x50, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd164[] = {
    0xFF, 0x2F, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd165[] = {
    0x83, 0xCC, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd166[] = {
    0x84, 0x33, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd167[] = {
    0xC0, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd168[] = {
    0xC1, 0x01, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd169[] = {
    0xC2, 0x0B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd170[] = {
    0xC3, 0x17, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd171[] = {
    0xC4, 0x22, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd172[] = {
    0xC5, 0x2A, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd173[] = {
    0xC6, 0x32, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd174[] = {
    0xC7, 0x38, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd175[] = {
    0xC8, 0x3E, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd176[] = {
    0xC9, 0x8D, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd177[] = {
    0xCA, 0x90, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd178[] = {
    0xCB, 0xA5, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd179[] = {
    0xCC, 0xB4, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd180[] = {
    0xCD, 0xBB, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd181[] = {
    0xCE, 0xB8, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd182[] = {
    0xCF, 0xBB, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd183[] = {
    0xD0, 0xBD, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd184[] = {
    0xD1, 0xCC, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd185[] = {
    0xD2, 0xDF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd186[] = {
    0xD3, 0xFE, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd187[] = {
    0xD4, 0x08, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd188[] = {
    0xD5, 0x90, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd189[] = {
    0xD6, 0x97, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd190[] = {
    0xD7, 0x9E, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd191[] = {
    0xD8, 0xA8, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd192[] = {
    0xD9, 0xB1, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd193[] = {
    0xDA, 0xBC, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd194[] = {
    0xDB, 0xD8, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd195[] = {
    0xDC, 0xEF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd196[] = {
    0xDD, 0xFF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd197[] = {
    0xDE, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd198[] = {
    0xDF, 0x28, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd199[] = {
    0xE0, 0x39, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd200[] = {
    0xE1, 0x3A, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd201[] = {
    0xE2, 0x44, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd202[] = {
    0xE3, 0x4E, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd203[] = {
    0xE4, 0x5B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd204[] = {
    0xE5, 0x65, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd205[] = {
    0xE6, 0x6B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd206[] = {
    0xE7, 0x71, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd207[] = {
    0xE8, 0x77, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd208[] = {
    0xE9, 0xD7, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd209[] = {
    0xEA, 0xD7, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd210[] = {
    0xEB, 0xF0, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd211[] = {
    0xEC, 0x02, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd212[] = {
    0xED, 0x07, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd213[] = {
    0xEE, 0x05, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd214[] = {
    0xEF, 0x07, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd215[] = {
    0xF0, 0x09, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd216[] = {
    0xF1, 0x18, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd217[] = {
    0xF2, 0x2A, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd218[] = {
    0xF3, 0x4B, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd219[] = {
    0xF4, 0x54, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd220[] = {
    0xF5, 0xB6, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd221[] = {
    0xF6, 0xBD, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd222[] = {
    0xF7, 0xC4, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd223[] = {
    0xF8, 0xCE, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd224[] = {
    0xF9, 0xD8, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd225[] = {
    0xFA, 0xE1, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd226[] = {
    0xFB, 0xED, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd227[] = {
    0xFC, 0xEF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd228[] = {
    0xFD, 0xFF, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd229[] = {
    0xFE, 0xF8, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd230[] = {
    0xFF, 0x2F, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd231[] = {
    0x83, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd232[] = {
    0x84, 0x00, 0x15, 0x80};


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd233[] = {
    0x11, 0x00, 0x05, 0x80};




static struct mipi_dsi_cmd cpn_l01_va_inx_nt51021_8p0_1200p_video_on_command[] = {
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd0, 0x06},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd1, 0x18},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd2, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd3, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd4, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd5, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd6, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd7, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd8, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd9, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd10, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd11, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd12, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd13, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd14, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd15, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd16, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd17, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd18, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd19, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd20, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd21, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd22, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd23, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd24, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd25, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd26, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd27, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd28, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd29, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd30, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd31, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd32, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd33, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd34, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd35, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd36, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd37, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd38, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd39, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd40, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd41, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd42, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd43, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd44, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd45, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd46, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd47, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd48, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd49, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd50, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd51, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd52, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd53, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd54, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd55, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd56, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd57, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd58, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd59, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd60, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd61, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd62, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd63, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd64, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd65, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd66, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd67, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd68, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd69, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd70, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd71, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd72, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd73, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd74, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd75, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd76, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd77, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd78, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd79, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd80, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd81, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd82, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd83, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd84, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd85, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd86, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd87, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd88, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd89, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd90, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd91, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd92, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd93, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd94, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd95, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd96, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd97, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd98, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd99, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd100, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd101, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd102, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd103, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd104, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd105, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd106, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd107, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd108, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd109, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd110, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd111, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd112, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd113, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd114, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd115, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd116, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd117, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd118, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd119, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd120, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd121, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd122, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd123, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd124, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd125, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd126, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd127, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd128, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd129, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd130, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd131, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd132, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd133, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd134, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd135, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd136, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd137, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd138, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd139, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd140, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd141, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd142, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd143, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd144, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd145, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd146, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd147, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd148, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd149, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd150, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd151, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd152, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd153, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd154, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd155, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd156, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd157, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd158, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd159, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd160, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd161, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd162, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd163, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd164, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd165, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd166, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd167, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd168, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd169, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd170, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd171, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd172, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd173, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd174, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd175, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd176, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd177, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd178, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd179, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd180, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd181, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd182, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd183, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd184, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd185, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd186, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd187, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd188, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd189, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd190, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd191, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd192, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd193, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd194, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd195, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd196, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd197, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd198, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd199, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd200, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd201, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd202, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd203, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd204, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd205, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd206, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd207, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd208, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd209, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd210, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd211, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd212, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd213, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd214, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd215, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd216, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd217, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd218, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd219, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd220, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd221, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd222, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd223, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd224, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd225, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd226, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd227, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd228, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd229, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd230, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd231, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd232, 0x00},
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_on_cmd233, 0x05}
};
#define CPN_L01_VA_INX_NT51021_8P0_1200P_VIDEO_ON_COMMAND 234


static char cpn_l01_va_inx_nt51021_8p0_1200p_video_off_cmd0[] = {
    0x10, 0x00, 0x15, 0x80};




static struct mipi_dsi_cmd cpn_l01_va_inx_nt51021_8p0_1200p_video_off_command[] = {
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_off_cmd0, 0x05}
};
#define CPN_L01_VA_INX_NT51021_8P0_1200P_VIDEO_OFF_COMMAND 1


static struct command_state cpn_l01_va_inx_nt51021_8p0_1200p_video_state = {
        0, 1 
};

/*-----------------------------------------------------------------------*/
/* Command mode panel                                                    */
/*-----------------------------------------------------------------------*/
static struct commandpanel_info cpn_l01_va_inx_nt51021_8p0_1200p_video_command_panel = {
        0, 1, 1, 0, 0, 0x2c, 0, 0, 0, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Video mode panel                                                      */
/*-----------------------------------------------------------------------*/
static struct videopanel_info cpn_l01_va_inx_nt51021_8p0_1200p_video_video_panel = {
        1, 0, 0, 0, 1, 1, 2, 0, 0x9 
};

/*-----------------------------------------------------------------------*/
/* Lane configuration                                                    */
/*-----------------------------------------------------------------------*/
static struct lane_configuration cpn_l01_va_inx_nt51021_8p0_1200p_video_lane_config = {
        4, 0, 1, 1, 1, 1, 1 
};

/*-----------------------------------------------------------------------*/
/* Panel timing                                                          */
/*-----------------------------------------------------------------------*/
static const uint32_t cpn_l01_va_inx_nt51021_8p0_1200p_video_timings[]= {
        0xF8, 0x3C, 0x28, 0x00, 0x6E, 0x72, 0x2E, 0x40, 0x30, 0x03, 0x04, 0x00 
};

static struct panel_timing cpn_l01_va_inx_nt51021_8p0_1200p_video_timing_info = {
        0, 4, 0x02, 0x2d 
};

/*-----------------------------------------------------------------------*/
/* Panel reset sequence                                                  */
/*-----------------------------------------------------------------------*/
static struct panel_reset_sequence cpn_l01_va_inx_nt51021_8p0_1200p_video_reset_seq = {
    { 1, 0, 1, }, { 5, 5, 5, }, 2
};

/*-----------------------------------------------------------------------*/
/* Backlight setting                                                     */
/*-----------------------------------------------------------------------*/
static struct backlight cpn_l01_va_inx_nt51021_8p0_1200p_video_backlight = {
        3, 2, 255, 1, 3, 0 
};

/*-----------------------------------------------------------------------*/
/* Labibb setting                                                        */
/*-----------------------------------------------------------------------*/
static struct labibb_desc cpn_l01_va_inx_nt51021_8p0_1200p_video_labibb = {
        1, 1, 5500000, 5500000, 5500000, 5500000, 3, 3, 1, 0 
};

/*-----------------------------------------------------------------------*/
/* turn on backlight delay                                               */
/*-----------------------------------------------------------------------*/
int cpn_l01_va_inx_nt51021_8p0_1200p_video_mdp_pipe_type  = MDSS_MDP_PIPE_TYPE_RGB;

int cpn_l01_va_inx_nt51021_8p0_1200p_video_dsi_pll_type  = DSI_PLL_TYPE_28NM;

int cpn_l01_va_inx_nt51021_8p0_1200p_video_mipi_signature  = 0xffff;

static const uint32_t cpn_l01_va_inx_nt51021_8p0_1200p_video_regulator_setting[]= {
        0x03, 0x08, 0x07, 0x00, 0x20, 0x07, 0x01 
};

/*-----------------------------------------------------------------------*/
/* platform Config                                                       */
/*-----------------------------------------------------------------------*/
static struct lcdkit_platform_config cpn_l01_va_inx_nt51021_8p0_1200p_video_panel_platform_config = {
        3, 1, 0, 0, 0, 0, 0x200, 0x20, 0, 33, 0, 1, 0, 38, 33, 0, 0, 
        50, 0, 0, 0, 0, 5500000, 5500000, 102, 20, 8556, 1, 1, 0, 0, 
        3, 1 
};

/*-----------------------------------------------------------------------*/
/* misc Information                                                      */
/*-----------------------------------------------------------------------*/
static struct lcdkit_misc_info cpn_l01_va_inx_nt51021_8p0_1200p_video_panel_misc_info = {
        0x1, 0, 1, 0x1, 0x0, 0x02, 0x02, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* delay ctrl                                                            */
/*-----------------------------------------------------------------------*/
static struct lcdkit_delay_ctrl cpn_l01_va_inx_nt51021_8p0_1200p_video_panel_delay_ctrl = {
        0, 30, 0, 0, 3, 3, 0, 0, 0, 500, 0, 20, 80, 50 
};

static char cpn_l01_va_inx_nt51021_8p0_1200p_video_backlight_cmd0[] = {
    0x9F, 0x00, 0x23, 0x80};




static struct mipi_dsi_cmd cpn_l01_va_inx_nt51021_8p0_1200p_video_backlight_command[] = {
{0x4, cpn_l01_va_inx_nt51021_8p0_1200p_video_backlight_cmd0, 0x00}
};
#define CPN_L01_VA_INX_NT51021_8P0_1200P_VIDEO_BACKLIGHT_COMMAND 1



static struct lcd_bias_voltage_info * cpn_l01_va_inx_nt51021_8p0_1200p_video_bias_ic_array[0];
 
#define CPN_L01_VA_INX_NT51021_8P0_1200P_VIDEO_BIAS_IC_ARRAY 0


static struct backlight_ic_info * cpn_l01_va_inx_nt51021_8p0_1200p_video_backlight_ic_array[0];
 
#define CPN_L01_VA_INX_NT51021_8P0_1200P_VIDEO_BACKLIGHT_IC_ARRAY 0


#endif /*_PANEL_CPN_L01_VA_INX_NT51021_8P0_1200P_VIDEO_H_*/
