/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*-------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = 1.1
 *-----------------------------------------------------------------------*/

#ifndef _PANEL_CPN_L09_VA_AUO_NT51021_8P0_1200P_VIDEO_H_

#define _PANEL_CPN_L09_VA_AUO_NT51021_8P0_1200P_VIDEO_H_
/*-----------------------------------------------------------------------*/
/* HEADER files                                                          */
/*-----------------------------------------------------------------------*/
#include "panel.h"

#include "lcdkit_bias_ic_common.h"

#include "lcd_bl.h"

/*-----------------------------------------------------------------------*/
/* Panel configuration                                                   */
/*-----------------------------------------------------------------------*/
static struct panel_config cpn_l09_va_auo_nt51021_8p0_1200p_video_panel_data = {
        "lcdkit_cpn_l09_va_auo_nt51021_8p0_1200p_video", "dsi:0:", 
        "auo_nt51021_8p0_1200p_video", 10, 0, "DISPLAY_1", 0, 964230000, 
        60, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel resolution                                                      */
/*-----------------------------------------------------------------------*/
static struct panel_resolution cpn_l09_va_auo_nt51021_8p0_1200p_video_panel_res = {
        1200, 1920, 64, 36, 4, 0, 106, 26, 2, 0, 0, 0, 0, 0, 0, 0, 
        0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel color information                                               */
/*-----------------------------------------------------------------------*/
static struct color_info cpn_l09_va_auo_nt51021_8p0_1200p_video_color = {
        24, 0, 0x00, 0, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel on/off command                                                  */
/*-----------------------------------------------------------------------*/
static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd0[] = {
    0x8F, 0xA5, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd1[] = {
    0x01, 0x00, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd2[] = {
    0x8F, 0xA5, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd3[] = {
    0x83, 0xBB, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd4[] = {
    0x84, 0x22, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd5[] = {
    0xA1, 0xFF, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd6[] = {
    0xA2, 0xF9, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd7[] = {
    0xA3, 0xF2, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd8[] = {
    0xA4, 0xED, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd9[] = {
    0xA5, 0xE5, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd10[] = {
    0xA6, 0xDF, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd11[] = {
    0xA7, 0xDE, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd12[] = {
    0xA8, 0xDA, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd13[] = {
    0xA9, 0xD3, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd14[] = {
    0xAA, 0xCF, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd15[] = {
    0xB4, 0x20, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd16[] = {
    0xB5, 0x32, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd17[] = {
    0xB6, 0x29, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd18[] = {
    0xAD, 0x06, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd19[] = {
    0x9A, 0x10, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd20[] = {
    0x94, 0xB8, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd21[] = {
    0x95, 0x00, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd22[] = {
    0x9A, 0x10, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd23[] = {
    0x96, 0x00, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd24[] = {
    0x90, 0x00, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd25[] = {
    0x83, 0xAA, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd26[] = {
    0x84, 0x11, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd27[] = {
    0xA9, 0x4B, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd28[] = {
    0x83, 0x00, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd29[] = {
    0x84, 0x00, 0x15, 0x80};


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd30[] = {
    0x11, 0x00, 0x05, 0x80};




static struct mipi_dsi_cmd cpn_l09_va_auo_nt51021_8p0_1200p_video_on_command[] = {
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd0, 0x06},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd1, 0x18},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd2, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd3, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd4, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd5, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd6, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd7, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd8, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd9, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd10, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd11, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd12, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd13, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd14, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd15, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd16, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd17, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd18, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd19, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd20, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd21, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd22, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd23, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd24, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd25, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd26, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd27, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd28, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd29, 0x00},
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_on_cmd30, 0x05}
};
#define CPN_L09_VA_AUO_NT51021_8P0_1200P_VIDEO_ON_COMMAND 31


static char cpn_l09_va_auo_nt51021_8p0_1200p_video_off_cmd0[] = {
    0x10, 0x00, 0x15, 0x80};




static struct mipi_dsi_cmd cpn_l09_va_auo_nt51021_8p0_1200p_video_off_command[] = {
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_off_cmd0, 0x05}
};
#define CPN_L09_VA_AUO_NT51021_8P0_1200P_VIDEO_OFF_COMMAND 1


static struct command_state cpn_l09_va_auo_nt51021_8p0_1200p_video_state = {
        0, 1 
};

/*-----------------------------------------------------------------------*/
/* Command mode panel                                                    */
/*-----------------------------------------------------------------------*/
static struct commandpanel_info cpn_l09_va_auo_nt51021_8p0_1200p_video_command_panel = {
        0, 1, 1, 0, 0, 0x2c, 0, 0, 0, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Video mode panel                                                      */
/*-----------------------------------------------------------------------*/
static struct videopanel_info cpn_l09_va_auo_nt51021_8p0_1200p_video_video_panel = {
        1, 0, 0, 0, 1, 1, 2, 0, 0x9 
};

/*-----------------------------------------------------------------------*/
/* Lane configuration                                                    */
/*-----------------------------------------------------------------------*/
static struct lane_configuration cpn_l09_va_auo_nt51021_8p0_1200p_video_lane_config = {
        4, 0, 1, 1, 1, 1, 1 
};

/*-----------------------------------------------------------------------*/
/* Panel timing                                                          */
/*-----------------------------------------------------------------------*/
static const uint32_t cpn_l09_va_auo_nt51021_8p0_1200p_video_timings[]= {
        0xF8, 0x3C, 0x28, 0x00, 0x6E, 0x72, 0x2E, 0x40, 0x30, 0x03, 0x04, 0x00 
};

static struct panel_timing cpn_l09_va_auo_nt51021_8p0_1200p_video_timing_info = {
        0, 4, 0x02, 0x2d 
};

/*-----------------------------------------------------------------------*/
/* Panel reset sequence                                                  */
/*-----------------------------------------------------------------------*/
static struct panel_reset_sequence cpn_l09_va_auo_nt51021_8p0_1200p_video_reset_seq = {
    { 1, 0, 1, }, { 5, 5, 5, }, 2
};

/*-----------------------------------------------------------------------*/
/* Backlight setting                                                     */
/*-----------------------------------------------------------------------*/
static struct backlight cpn_l09_va_auo_nt51021_8p0_1200p_video_backlight = {
        3, 2, 255, 1, 3, 0 
};

/*-----------------------------------------------------------------------*/
/* Labibb setting                                                        */
/*-----------------------------------------------------------------------*/
static struct labibb_desc cpn_l09_va_auo_nt51021_8p0_1200p_video_labibb = {
        1, 1, 5500000, 5500000, 5500000, 5500000, 3, 3, 1, 0 
};

/*-----------------------------------------------------------------------*/
/* turn on backlight delay                                               */
/*-----------------------------------------------------------------------*/
int cpn_l09_va_auo_nt51021_8p0_1200p_video_mdp_pipe_type  = MDSS_MDP_PIPE_TYPE_RGB;

int cpn_l09_va_auo_nt51021_8p0_1200p_video_dsi_pll_type  = DSI_PLL_TYPE_28NM;

int cpn_l09_va_auo_nt51021_8p0_1200p_video_mipi_signature  = 0xffff;

static const uint32_t cpn_l09_va_auo_nt51021_8p0_1200p_video_regulator_setting[]= {
        0x03, 0x08, 0x07, 0x00, 0x20, 0x07, 0x01 
};

/*-----------------------------------------------------------------------*/
/* platform Config                                                       */
/*-----------------------------------------------------------------------*/
static struct lcdkit_platform_config cpn_l09_va_auo_nt51021_8p0_1200p_video_panel_platform_config = {
        3, 1, 0, 0, 0, 0, 0x200, 0x20, 0, 33, 0, 1, 0, 38, 33, 0, 0, 
        50, 0, 0, 0, 0, 5500000, 5500000, 102, 20, 8556, 1, 1, 0, 0, 
        3, 1 
};

/*-----------------------------------------------------------------------*/
/* misc Information                                                      */
/*-----------------------------------------------------------------------*/
static struct lcdkit_misc_info cpn_l09_va_auo_nt51021_8p0_1200p_video_panel_misc_info = {
        0x1, 0, 1, 0x1, 0x0, 0x02, 0x02, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* delay ctrl                                                            */
/*-----------------------------------------------------------------------*/
static struct lcdkit_delay_ctrl cpn_l09_va_auo_nt51021_8p0_1200p_video_panel_delay_ctrl = {
        0, 30, 0, 0, 3, 3, 0, 0, 0, 500, 0, 20, 80, 50 
};

static char cpn_l09_va_auo_nt51021_8p0_1200p_video_backlight_cmd0[] = {
    0x9F, 0x00, 0x23, 0x80};




static struct mipi_dsi_cmd cpn_l09_va_auo_nt51021_8p0_1200p_video_backlight_command[] = {
{0x4, cpn_l09_va_auo_nt51021_8p0_1200p_video_backlight_cmd0, 0x00}
};
#define CPN_L09_VA_AUO_NT51021_8P0_1200P_VIDEO_BACKLIGHT_COMMAND 1



static struct lcd_bias_voltage_info * cpn_l09_va_auo_nt51021_8p0_1200p_video_bias_ic_array[0];
 
#define CPN_L09_VA_AUO_NT51021_8P0_1200P_VIDEO_BIAS_IC_ARRAY 0


static struct backlight_ic_info * cpn_l09_va_auo_nt51021_8p0_1200p_video_backlight_ic_array[0];
 
#define CPN_L09_VA_AUO_NT51021_8P0_1200P_VIDEO_BACKLIGHT_IC_ARRAY 0


#endif /*_PANEL_CPN_L09_VA_AUO_NT51021_8P0_1200P_VIDEO_H_*/
