/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*-------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = 1.1
 *-----------------------------------------------------------------------*/

#ifndef _PANEL_KOB_W09C_VA_INX_JD9367_8P0_800P_VIDEO_H_

#define _PANEL_KOB_W09C_VA_INX_JD9367_8P0_800P_VIDEO_H_
/*-----------------------------------------------------------------------*/
/* HEADER files                                                          */
/*-----------------------------------------------------------------------*/
#include "panel.h"

#include "lcdkit_bias_ic_common.h"

#include "lcd_bl.h"

/*-----------------------------------------------------------------------*/
/* Panel configuration                                                   */
/*-----------------------------------------------------------------------*/
static struct panel_config kob_w09c_va_inx_jd9367_8p0_800p_video_panel_data = {
        "lcdkit_kob_w09c_va_inx_jd9367_8p0_800p_video", "dsi:0:", "inx_jd9367_8p0_800p_video", 
        10, 0, "DISPLAY_1", 0, 423260000, 
        60, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel resolution                                                      */
/*-----------------------------------------------------------------------*/
static struct panel_resolution kob_w09c_va_inx_jd9367_8p0_800p_video_panel_res = {
        800, 1280, 40, 40, 8, 0, 20, 20, 4, 0, 0, 0, 0, 0, 0, 0, 0, 
        0 
};

/*-----------------------------------------------------------------------*/
/* Panel color information                                               */
/*-----------------------------------------------------------------------*/
static struct color_info kob_w09c_va_inx_jd9367_8p0_800p_video_color = {
        24, 0, 0x00, 0, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel on/off command                                                  */
/*-----------------------------------------------------------------------*/
static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd0[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xE0, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd1[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xE1, 0x93, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd2[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xE2, 0x65, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd3[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xE3, 0xF8, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd4[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x80, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd5[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x70, 0x10, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd6[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x71, 0x13, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd7[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x72, 0x06, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd8[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xE0, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd9[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd10[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x01, 0x7D, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd11[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x03, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd12[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x04, 0x7D, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd13[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0C, 0x74, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd14[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x17, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd15[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x18, 0xDF, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd16[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x19, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd17[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x1A, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd18[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x1B, 0xDF, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd19[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x1C, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd20[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x1F, 0x79, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd21[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x20, 0x2D, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd22[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x21, 0x2D, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd23[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x22, 0x0E, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd24[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x37, 0x09, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd25[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x38, 0x04, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd26[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x39, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd27[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3A, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd28[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3C, 0x70, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd29[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3D, 0xFF, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd30[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3E, 0xFF, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd31[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3F, 0x7F, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd32[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x40, 0x06, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd33[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x41, 0xA0, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd34[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x43, 0x14, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd35[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x44, 0x17, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd36[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x45, 0x30, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd37[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4B, 0x04, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd38[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x55, 0x0D, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd39[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x56, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd40[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x57, 0x88, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd41[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x58, 0x0A, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd42[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x59, 0x2A, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd43[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5A, 0x37, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd44[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5B, 0x19, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd45[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5C, 0x16, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd46[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5D, 0x7B, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd47[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5E, 0x52, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd48[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5F, 0x3F, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd49[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x60, 0x32, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd50[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x61, 0x2E, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd51[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x62, 0x1E, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd52[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x63, 0x22, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd53[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x64, 0x0C, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd54[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x65, 0x24, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd55[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x66, 0x24, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd56[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x67, 0x22, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd57[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x68, 0x3D, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd58[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x69, 0x29, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd59[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6A, 0x33, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd60[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6B, 0x27, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd61[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6C, 0x2A, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd62[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6D, 0x20, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd63[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6E, 0x10, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd64[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6F, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd65[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x70, 0x7B, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd66[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x71, 0x52, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd67[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x72, 0x3F, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd68[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x73, 0x32, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd69[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x74, 0x2E, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd70[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x75, 0x1E, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd71[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x76, 0x22, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd72[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x77, 0x0C, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd73[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x78, 0x24, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd74[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x79, 0x24, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd75[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7A, 0x22, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd76[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7B, 0x3D, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd77[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7C, 0x29, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd78[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7D, 0x33, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd79[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7E, 0x27, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd80[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7F, 0x2A, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd81[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x80, 0x20, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd82[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x81, 0x10, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd83[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x82, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd84[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xE0, 0x02, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd85[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x00, 0x40, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd86[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x01, 0x44, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd87[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x02, 0x46, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd88[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x03, 0x48, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd89[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x04, 0x4A, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd90[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x05, 0x4C, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd91[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x06, 0x4E, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd92[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x07, 0x57, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd93[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x08, 0x77, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd94[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x09, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd95[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0A, 0x50, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd96[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0B, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd97[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0C, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd98[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0D, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd99[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0E, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd100[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0F, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd101[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x10, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd102[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x11, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd103[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x12, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd104[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x13, 0x52, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd105[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x14, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd106[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x15, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd107[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x16, 0x41, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd108[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x17, 0x45, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd109[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x18, 0x47, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd110[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x19, 0x49, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd111[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x1A, 0x4B, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd112[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x1B, 0x4D, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd113[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x1C, 0x4F, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd114[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x1D, 0x57, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd115[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x1E, 0x77, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd116[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x1F, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd117[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x20, 0x51, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd118[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x21, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd119[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x22, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd120[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x23, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd121[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x24, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd122[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x25, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd123[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x26, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd124[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x27, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd125[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x28, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd126[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x29, 0x53, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd127[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2A, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd128[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2B, 0x55, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd129[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2C, 0x11, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd130[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2D, 0x0F, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd131[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2E, 0x0D, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd132[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2F, 0x0B, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd133[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x30, 0x09, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd134[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x31, 0x07, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd135[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x32, 0x05, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd136[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x33, 0x17, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd137[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x34, 0x17, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd138[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x35, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd139[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x36, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd140[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x37, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd141[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x38, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd142[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x39, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd143[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3A, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd144[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3B, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd145[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3C, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd146[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3D, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd147[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3E, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd148[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3F, 0x13, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd149[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x40, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd150[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x41, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd151[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x42, 0x10, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd152[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x43, 0x0E, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd153[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x44, 0x0C, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd154[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x45, 0x0A, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd155[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x46, 0x08, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd156[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x47, 0x06, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd157[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x48, 0x04, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd158[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x49, 0x17, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd159[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4A, 0x17, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd160[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4B, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd161[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4C, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd162[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4D, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd163[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4E, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd164[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4F, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd165[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x50, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd166[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x51, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd167[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x52, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd168[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x53, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd169[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x54, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd170[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x55, 0x12, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd171[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x56, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd172[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x57, 0x15, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd173[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x58, 0x40, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd174[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x59, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd175[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5A, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd176[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5B, 0x10, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd177[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5C, 0x10, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd178[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5D, 0x40, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd179[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5E, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd180[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5F, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd181[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x60, 0x30, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd182[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x61, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd183[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x62, 0x04, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd184[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x63, 0x6A, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd185[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x64, 0x6A, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd186[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x65, 0x75, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd187[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x66, 0x17, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd188[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x67, 0xB4, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd189[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x68, 0x12, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd190[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x69, 0x6A, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd191[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6A, 0x6A, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd192[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6B, 0x04, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd193[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6C, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd194[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6D, 0x04, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd195[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6E, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd196[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6F, 0x88, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd197[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x70, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd198[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x71, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd199[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x72, 0x06, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd200[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x73, 0x7B, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd201[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x74, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd202[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x75, 0xBC, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd203[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x76, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd204[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x77, 0x0D, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd205[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x78, 0x2C, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd206[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x79, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd207[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7A, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd208[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7B, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd209[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7C, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd210[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7D, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd211[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7E, 0x7B, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd212[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xE0, 0x04, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd213[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x09, 0x10, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd214[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x0E, 0x48, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd215[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2B, 0x2B, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd216[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2E, 0x44, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd217[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x41, 0xFF, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd218[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xE0, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd219[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xAF, 0x20, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd220[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xE0, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd221[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xE6, 0x02, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd222[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xE7, 0x06, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd223[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x55, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd224[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x53, 0x2C, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd225[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x11, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd226[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xE0, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd227[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xAB, 0x0E, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd228[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2B, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd229[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x2C, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd230[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x30, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd231[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x31, 0xD5, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd232[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x32, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd233[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x33, 0xD3, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd234[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x34, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd235[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x35, 0xCB, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd236[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x36, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd237[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x37, 0xC1, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd238[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x38, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd239[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x39, 0xB9, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd240[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3A, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd241[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3B, 0xA9, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd242[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3C, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd243[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3D, 0x9B, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd244[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3E, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd245[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x3F, 0x7C, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd246[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x40, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd247[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x41, 0x5E, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd248[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x42, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd249[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x43, 0x20, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd250[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x44, 0x02, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd251[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x45, 0xE2, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd252[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x46, 0x02, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd253[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x47, 0x69, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd254[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x48, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd255[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x49, 0xEF, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd256[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4A, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd257[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4B, 0xEB, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd258[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4C, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd259[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4D, 0x73, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd260[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4E, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd261[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x4F, 0xFA, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd262[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x50, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd263[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x51, 0xBE, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd264[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x52, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd265[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x53, 0x7F, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd266[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x54, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd267[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x55, 0x5B, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd268[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x56, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd269[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x57, 0x35, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd270[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x58, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd271[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x59, 0x26, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd272[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5A, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd273[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5B, 0x18, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd274[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5C, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd275[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5D, 0x11, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd276[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5E, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd277[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x5F, 0x0A, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd278[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x60, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd279[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x61, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd280[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x62, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd281[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x63, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd282[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x64, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd283[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x65, 0xC3, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd284[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x66, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd285[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x67, 0xC1, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd286[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x68, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd287[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x69, 0xB9, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd288[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6A, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd289[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6B, 0xB2, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd290[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6C, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd291[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6D, 0xAA, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd292[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6E, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd293[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x6F, 0x9B, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd294[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x70, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd295[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x71, 0x8F, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd296[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x72, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd297[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x73, 0x70, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd298[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x74, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd299[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x75, 0x54, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd300[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x76, 0x03, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd301[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x77, 0x16, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd302[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x78, 0x02, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd303[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x79, 0xD9, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd304[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7A, 0x02, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd305[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7B, 0x61, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd306[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7C, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd307[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7D, 0xEA, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd308[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7E, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd309[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x7F, 0xE6, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd310[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x80, 0x01, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd311[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x81, 0x6F, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd312[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x82, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd313[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x83, 0xF6, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd314[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x84, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd315[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x85, 0xB9, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd316[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x86, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd317[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x87, 0x7D, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd318[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x88, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd319[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x89, 0x5C, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd320[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x8A, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd321[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x8B, 0x37, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd322[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x8C, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd323[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x8D, 0x27, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd324[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x8E, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd325[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x8F, 0x19, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd326[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x90, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd327[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x91, 0x12, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd328[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x92, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd329[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x93, 0x0B, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd330[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x94, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd331[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x95, 0x04, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd332[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x96, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd333[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x97, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd334[] = {
    0x02, 0x00, 0x39, 0xC0,
    0xE0, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd335[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x29, 0x00, 0xFF, 0xFF};




static struct mipi_dsi_cmd kob_w09c_va_inx_jd9367_8p0_800p_video_on_command[] = {
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd0, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd1, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd2, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd3, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd4, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd5, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd6, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd7, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd8, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd9, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd10, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd11, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd12, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd13, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd14, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd15, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd16, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd17, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd18, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd19, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd20, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd21, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd22, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd23, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd24, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd25, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd26, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd27, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd28, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd29, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd30, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd31, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd32, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd33, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd34, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd35, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd36, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd37, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd38, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd39, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd40, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd41, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd42, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd43, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd44, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd45, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd46, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd47, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd48, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd49, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd50, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd51, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd52, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd53, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd54, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd55, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd56, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd57, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd58, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd59, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd60, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd61, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd62, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd63, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd64, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd65, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd66, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd67, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd68, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd69, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd70, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd71, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd72, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd73, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd74, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd75, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd76, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd77, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd78, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd79, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd80, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd81, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd82, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd83, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd84, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd85, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd86, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd87, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd88, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd89, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd90, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd91, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd92, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd93, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd94, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd95, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd96, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd97, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd98, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd99, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd100, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd101, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd102, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd103, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd104, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd105, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd106, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd107, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd108, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd109, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd110, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd111, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd112, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd113, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd114, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd115, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd116, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd117, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd118, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd119, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd120, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd121, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd122, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd123, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd124, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd125, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd126, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd127, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd128, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd129, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd130, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd131, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd132, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd133, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd134, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd135, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd136, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd137, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd138, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd139, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd140, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd141, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd142, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd143, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd144, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd145, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd146, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd147, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd148, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd149, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd150, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd151, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd152, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd153, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd154, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd155, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd156, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd157, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd158, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd159, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd160, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd161, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd162, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd163, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd164, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd165, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd166, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd167, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd168, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd169, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd170, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd171, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd172, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd173, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd174, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd175, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd176, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd177, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd178, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd179, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd180, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd181, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd182, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd183, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd184, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd185, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd186, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd187, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd188, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd189, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd190, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd191, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd192, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd193, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd194, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd195, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd196, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd197, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd198, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd199, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd200, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd201, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd202, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd203, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd204, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd205, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd206, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd207, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd208, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd209, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd210, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd211, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd212, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd213, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd214, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd215, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd216, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd217, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd218, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd219, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd220, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd221, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd222, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd223, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd224, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd225, 0x78},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd226, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd227, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd228, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd229, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd230, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd231, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd232, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd233, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd234, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd235, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd236, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd237, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd238, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd239, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd240, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd241, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd242, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd243, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd244, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd245, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd246, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd247, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd248, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd249, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd250, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd251, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd252, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd253, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd254, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd255, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd256, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd257, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd258, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd259, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd260, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd261, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd262, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd263, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd264, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd265, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd266, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd267, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd268, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd269, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd270, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd271, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd272, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd273, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd274, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd275, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd276, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd277, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd278, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd279, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd280, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd281, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd282, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd283, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd284, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd285, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd286, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd287, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd288, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd289, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd290, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd291, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd292, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd293, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd294, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd295, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd296, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd297, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd298, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd299, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd300, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd301, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd302, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd303, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd304, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd305, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd306, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd307, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd308, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd309, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd310, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd311, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd312, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd313, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd314, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd315, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd316, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd317, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd318, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd319, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd320, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd321, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd322, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd323, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd324, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd325, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd326, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd327, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd328, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd329, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd330, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd331, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd332, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd333, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd334, 0x00},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_on_cmd335, 0x20}
};
#define KOB_W09C_VA_INX_JD9367_8P0_800P_VIDEO_ON_COMMAND 336


static char kob_w09c_va_inx_jd9367_8p0_800p_video_off_cmd0[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x28, 0x00, 0xFF, 0xFF};


static char kob_w09c_va_inx_jd9367_8p0_800p_video_off_cmd1[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x10, 0x00, 0xFF, 0xFF};




static struct mipi_dsi_cmd kob_w09c_va_inx_jd9367_8p0_800p_video_off_command[] = {
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_off_cmd0, 0x20},
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_off_cmd1, 0x78}
};
#define KOB_W09C_VA_INX_JD9367_8P0_800P_VIDEO_OFF_COMMAND 2


static struct command_state kob_w09c_va_inx_jd9367_8p0_800p_video_state = {
        0, 0 
};

/*-----------------------------------------------------------------------*/
/* Command mode panel                                                    */
/*-----------------------------------------------------------------------*/
static struct commandpanel_info kob_w09c_va_inx_jd9367_8p0_800p_video_command_panel = {
        0, 1, 1, 0, 0, 0x2c, 0, 0, 0, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* Video mode panel                                                      */
/*-----------------------------------------------------------------------*/
static struct videopanel_info kob_w09c_va_inx_jd9367_8p0_800p_video_video_panel = {
        1, 0, 0, 0, 1, 1, 2, 0, 0x9 
};

/*-----------------------------------------------------------------------*/
/* Lane configuration                                                    */
/*-----------------------------------------------------------------------*/
static struct lane_configuration kob_w09c_va_inx_jd9367_8p0_800p_video_lane_config = {
        4, 0, 1, 1, 1, 1, 0 
};

/*-----------------------------------------------------------------------*/
/* Panel timing                                                          */
/*-----------------------------------------------------------------------*/
static const uint32_t kob_w09c_va_inx_jd9367_8p0_800p_video_timings[]= {
        0x82, 0x1A, 0x12, 0x00, 0x3E, 0x42, 0x16, 0x1E, 0x14, 0x03, 0x04, 0x00 
};

static struct panel_timing kob_w09c_va_inx_jd9367_8p0_800p_video_timing_info = {
        0, 4, 0x04, 0x1B 
};

/*-----------------------------------------------------------------------*/
/* Panel reset sequence                                                  */
/*-----------------------------------------------------------------------*/
static struct panel_reset_sequence kob_w09c_va_inx_jd9367_8p0_800p_video_reset_seq = {
    { 1, 0, 1, }, { 15, 10, 20, }, 2
};

/*-----------------------------------------------------------------------*/
/* Backlight setting                                                     */
/*-----------------------------------------------------------------------*/
static struct backlight kob_w09c_va_inx_jd9367_8p0_800p_video_backlight = {
        3, 20, 2047, 1, 3, 0 
};

/*-----------------------------------------------------------------------*/
/* Labibb setting                                                        */
/*-----------------------------------------------------------------------*/
static struct labibb_desc kob_w09c_va_inx_jd9367_8p0_800p_video_labibb = {
        1, 1, 5500000, 5500000, 5500000, 5500000, 3, 3, 1, 0 
};

/*-----------------------------------------------------------------------*/
/* turn on backlight delay                                               */
/*-----------------------------------------------------------------------*/
int kob_w09c_va_inx_jd9367_8p0_800p_video_mdp_pipe_type  = MDSS_MDP_PIPE_TYPE_RGB;

int kob_w09c_va_inx_jd9367_8p0_800p_video_dsi_pll_type  = DSI_PLL_TYPE_28NM;

int kob_w09c_va_inx_jd9367_8p0_800p_video_mipi_signature  = 0xffff;

static const uint32_t kob_w09c_va_inx_jd9367_8p0_800p_video_regulator_setting[]= {
        0x03, 0x08, 0x07, 0x00, 0x20, 0x07, 0x01 
};

/*-----------------------------------------------------------------------*/
/* platform Config                                                       */
/*-----------------------------------------------------------------------*/
static struct lcdkit_platform_config kob_w09c_va_inx_jd9367_8p0_800p_video_panel_platform_config = {
        3, 1, 0, 1, 0, 0, 0x20, 0x20, 0, 99, 0, 60, 0, 8, 0, 0, 0, 
        45, 93, 0, 0, 0, 5500000, 5500000, 70, 20, 36923, 2, 1, 1, 0, 
        0, 0 
};

/*-----------------------------------------------------------------------*/
/* misc Information                                                      */
/*-----------------------------------------------------------------------*/
static struct lcdkit_misc_info kob_w09c_va_inx_jd9367_8p0_800p_video_panel_misc_info = {
        0x1, 0, 1, 0x1, 0x0, 0x02, 0x01, 1, 0, 0 
};

/*-----------------------------------------------------------------------*/
/* delay ctrl                                                            */
/*-----------------------------------------------------------------------*/
static struct lcdkit_delay_ctrl kob_w09c_va_inx_jd9367_8p0_800p_video_panel_delay_ctrl = {
        6, 6, 0, 0, 3, 3, 0, 0, 0, 0, 0, 120, 0, 50 
};

static char kob_w09c_va_inx_jd9367_8p0_800p_video_backlight_cmd0[] = {
    0x02, 0x00, 0x39, 0xC0,
    0x51, 0x00, 0xFF, 0xFF};




static struct mipi_dsi_cmd kob_w09c_va_inx_jd9367_8p0_800p_video_backlight_command[] = {
{0x8, kob_w09c_va_inx_jd9367_8p0_800p_video_backlight_cmd0, 0x00}
};
#define KOB_W09C_VA_INX_JD9367_8P0_800P_VIDEO_BACKLIGHT_COMMAND 1



static struct lcd_bias_voltage_info * kob_w09c_va_inx_jd9367_8p0_800p_video_bias_ic_array[0];
 
#define KOB_W09C_VA_INX_JD9367_8P0_800P_VIDEO_BIAS_IC_ARRAY 0


static struct backlight_ic_info * kob_w09c_va_inx_jd9367_8p0_800p_video_backlight_ic_array[0];
 
#define KOB_W09C_VA_INX_JD9367_8P0_800P_VIDEO_BACKLIGHT_IC_ARRAY 0


#endif /*_PANEL_KOB_W09C_VA_INX_JD9367_8P0_800P_VIDEO_H_*/
